#!/bin/bash
export BASE_DIR=$(dirname "$0")
source $BASE_DIR/vars.sh

NAME=$1

if [ -e "$RUN_DIR/$NAME.pid" ]; then
    echo "Stopping VM.."
    $BASE_DIR/kill $NAME
fi

echo "Removing disk..."
rm -rf $VM_DIR/$NAME.*
rm -rf $RUN_DIR/$NAME.*
