#!/bin/bash
pushd `dirname $0` > /dev/null
export BASE_DIR=`pwd -P`
popd > /dev/null

source $BASE_DIR/vars.sh

NAME=$1
KEY=$2
CPU=$3
MEM=$4
STORAGE=$5
PID_FILE=$RUN_DIR/$NAME.pid
MONITOR_FILE=$VM_DIR/$NAME.sock

DISK=${VM_DIR}/$NAME.img
MAC_ADDR=`printf '54:52:00:%02X:%02X:%02X\n' $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256))`

if [ -z "$BASE_DISK" ]; then
    echo "you must specify the BASE_DISK env var"
fi

if [ -z "$NAME" ] || [ -z "$CPU" ] || [ -z "$MEM" ] || [ -z "$STORAGE" ]; then
    echo "Usage: $0 <name> <ssh-pub-key> <cpu> <mem-in-mb> <storage-in-gb>"
    exit 1
fi

echo $MAC_ADDR > $VM_DIR/$NAME.mac

cat << EOF > $VM_DIR/$NAME.conf
NAME=$NAME
KEY="$KEY"
CPU=$CPU
MEM=$MEM
STORAGE=$STORAGE
PID_FILE=$PID_FILE
MONITOR_FILE=$MONITOR_FILE
DISK=$DISK
MAC_ADDR=$MAC_ADDR
EOF

echo "Cloning disk..."
qemu-img convert -O raw $BASE_DISK $DISK

echo "Resizing disk..."
qemu-img resize $DISK ${STORAGE}G

start_vm

if [ ! -z "$KEY" ]; then
    update_ssh_key
fi

echo "Instance created: name=$NAME ip=$IP"
