#!/bin/bash
pushd `dirname $0` > /dev/null
export BASE_DIR=`pwd -P`
popd > /dev/null

source $BASE_DIR/vars.sh

NAME=$1

if [ -e "$RUN_DIR/$NAME.pid" ]; then
    echo "Stopping VM.."
    kill -9 `cat $RUN_DIR/$NAME.pid`
fi

echo "Removing interface..."

echo "Removing disk..."
rm -rf $VM_DIR/$NAME.*
rm -rf $RUN_DIR/$NAME.*
